catalearn_child:
  build: .
  command: ./node_modules/.bin/nodemon server.js
  environment: 
    NODE_ENV: development
  ports:
    - "80:80"
  volumes:
    - .:/home/app/catalearn_child
    - /home/app/catalearn_child/node_modules